---

- name: Set SCL PHP timezone
  replace:
    dest: "/etc/opt/rh/{{sclmodphp_version}}/php.ini"
    regexp: >
      ^;date.timezone =$
    replace: "date.timezone = America/Chicago"

- name: Enable SCL PHP for interactive users
  template:
    src: enablephp.sh.j2
    dest: /etc/profile.d/enablephp.sh
    mode: 0755
    owner: root
    group: wheel
  when: sclmodphp_global

- name: Allow apache group access to web logs
  file:
    path: "/var/log/{{sclmodphp_httpd_version}}"
    mode: 0750
    owner: root
    group: apache

- name: Ensure php cache-utils path exists
  file:
    path: /opt/php/cache-utils
    owner: apache
    group: apache
    state: directory

- name: Copy cache control scripts
  copy:
    src: "{{ item }}"
    dest: /opt/php/cache-utils
    mode: 0755
    owner: apache
    group: apache
  loop:
    - opcache.php
    - cache_clear.php

- name: Copy cache control httpd config
  copy:
    src: cache-control.conf
    dest: "/opt/rh/{{sclmodphp_httpd_version}}/root/etc/httpd/conf.d"
    owner: apache
    group: apache

- name: Copy ssl config
  copy:
    src:  00ssl.include
    dest: "/opt/rh/{{sclmodphp_httpd_version}}/root/etc/httpd/conf.d"
    owner: apache
    group: apache

- name: Set environment variables for apache
  template:
    src: sysconfig-httpd.j2
    dest: "/opt/rh/{{sclmodphp_httpd_version}}/root/etc/sysconfig/httpd"

- name: Install php.ini
  template:
    src: php.ini.j2
    dest: /etc/opt/rh/{{sclmodphp_version}}/php.ini
    mode: 0644
    owner: root
    group: wheel




