---

- name: Set SCL PHP timezone
  replace:
    dest: "/etc/opt/rh/{{sclmodphp_version}}/php.ini"
    regexp: >
      ^;date.timezone =$
    replace: "date.timezone = America/Chicago"

- name: Enable SCL PHP for interactive users
  template:
    src: enablephp.sh.j2
    dest: /etc/profile.d/enablephp.sh
    mode: 0755
    owner: root
    group: wheel
  when: sclmodphp_global

 
